spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mySelf@123
    url: jdbc:mysql://47.98.112.186:3306/cloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
