server:
  port: 8761
  servlet:
    context-path: /discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka/
    register-with-eureka: false
    fetch-registry: false #是否从Eureka中获取注册信息
spring:
  application:
    name: eureka
