server:
  port: 8081
  servlet:
    context-path: /user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka/
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mySelf@123
    url: jdbc:mysql://47.98.112.186:3306/SpringCloud_Sell
env: dev
